### ISSUE TITLE
Recommended way to deploy embedded app to prod

### ISSUE THREAD

**Issue by toaler** [jetty-project/embedded-servlet-3.1#4]
How do you envision packaging EmbedMe along with the corresponding webapp?

I want to be able to just push the jars/wars to production and execute EmbedMe via java cli.  I'm struggling to work out how to do this.

What is the recommended why to package up this project if I only can ship *jars to production?  

How do I avoid duplicating jars within the war (WEB-INF/lib) vs the jar's needed by org.eclipse.jetty.demo.EmbedMe?

**Comment by joakime** [comment]
Traditionally, the embedded-jetty usage can be any of a variety of setups.

The one you mentioned about having only the war to ship is possible, and that's often called a "live war" (see jenkins for a real world example).  The organization of a live war is something that is very project specific and organized in dozens of different ways.

The fundamentals would be to have a `META-INF/MANIFEST.MF` file with a `Main-Class` entry that point to BootstrapEmbedMe which is in the root of your WAR file.

The BootstrapEmbedMe implementation needs to create a private classpath with the jetty server jars obtained from a non-live directory in your WAR file. (so `WEB-INF/classes` and `WEB-INF/lib` are inappropriate locations for this.  Consider `META-INF/jetty/` as a good location.  Once this private classpath is created, the EmbedMe is dynamically loaded within that private classpath and starts the server.

Another (far more common) approach is to skip the WAR file entirely, and use a `ServletContextHandler` (instead of a `WebAppContext`) packaged into a uber-jar with a `Main-Class` manifest to kick off the server.

I should write up an example of both of these.

However, I don't think it would be appropriate to muddy this project with those examples, it would likely be new projects.

**Comment by toaler** [comment]
Thanks for the reply.  Examples of the approaches would be golden.

I'll give what you explained a go.
